# Numpy Worksheet — Tasks

In [7]:
# Task 1: Initialize an empty array with size 2x2
import numpy as np
empty_arr = np.empty((2, 2))
empty_arr

array([[4.12340028e-315, 0.00000000e+000],
       [5.77218080e-317, 5.77056422e-317]])

In [8]:
# Task 2: Initialize an all-one array with size 4x2
ones_arr = np.ones((4, 2))
ones_arr

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [9]:
# Task 3: New array filled with given value
full_arr = np.full((3, 3), 7)
full_arr

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [10]:
# Task 4: New zeros array with same shape/type
arr = np.array([[1, 2, 3], [4, 5, 6]])
zeros_like_arr = np.zeros_like(arr)
zeros_like_arr

array([[0, 0, 0],
       [0, 0, 0]])

In [11]:
# Task 5: New ones array with same shape/type
ones_like_arr = np.ones_like(arr)
ones_like_arr

array([[1, 1, 1],
       [1, 1, 1]])

In [12]:
# Task 6: Convert list to numpy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
numpy_array

array([1, 2, 3, 4])

In [13]:
# Task 7: Array from 10 to 49
arr_10_49 = np.arange(10, 50)
arr_10_49

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [14]:
# Task 8: 3x3 matrix from 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)
matrix_3x3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
# Task 9: Identity matrix 3x3
identity_3x3 = np.eye(3)
identity_3x3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [46]:
# Task 10: Random array of size 30 and mean
rand_30 = np.random.random(30)
rand_30.mean()

np.float64(0.6141917227712689)

In [17]:
# Task 11: 10x10 random array min max
rand_10x10 = np.random.random((10, 10))
(rand_10x10.min(), rand_10x10.max())

(np.float64(0.012304085526722797), np.float64(0.9695646282712104))

In [18]:
# Task 12: Replace 5th element with 1
z = np.zeros(10)
z[4] = 1
z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [19]:
# Task 13: Reverse array
arr = np.array([1, 2, 0, 0, 4, 0])
arr[::-1]

array([0, 4, 0, 0, 2, 1])

In [20]:
# Task 14: Border ones, inside zeros
border_arr = np.ones((5, 5))
border_arr[1:-1, 1:-1] = 0
border_arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
# Task 15: Checkerboard 8x8
checkerboard = np.zeros((8, 8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
checkerboard

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [22]:
# Task 16: Add arrays
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
x + y

array([[ 6,  8],
       [10, 13]])

In [23]:
# Task 17: Subtract arrays
x - y

array([[-4, -4],
       [-4, -3]])

In [24]:
# Task 18: Multiply by integer
x * 3

array([[ 3,  6],
       [ 9, 15]])

In [25]:
# Task 19: Square elements
x ** 2

array([[ 1,  4],
       [ 9, 25]])

In [26]:
# Task 20: Dot products
v = np.array([9,10])
w = np.array([11,12])
(np.dot(v,w), np.dot(x,v), np.dot(x,y))

(np.int64(219),
 array([29, 77]),
 array([[19, 22],
        [50, 58]]))

In [27]:
# Task 21: Concatenate x & y along rows
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 5],
       [5, 6],
       [7, 8]])

In [49]:
# Task 22: Concatenate v & w along columns
np.column_stack((v, w))

array([ 9, 10, 11, 12])

In [29]:
# Task 23: Error check: concatenate x & v
try:
    bad = np.concatenate((x, v))
except Exception as e:
    print('Error:', e)

Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


In [30]:
# Task 24: Prove A * A^-1 = I
A = np.array([[3,4],[7,8]])
A @ np.linalg.inv(A)

array([[1.00000000e+00, 0.00000000e+00],
       [1.77635684e-15, 1.00000000e+00]])

In [31]:
# Task 25: Show AB != BA
B = np.array([[5,3],[2,1]])
(A @ B, B @ A)

(array([[23, 13],
        [51, 29]]),
 array([[36, 44],
        [13, 16]]))

In [32]:
# Task 26: (AB)^T = B^T A^T
((A @ B).T, B.T @ A.T)

(array([[23, 51],
        [13, 29]]),
 array([[23, 51],
        [13, 29]]))

In [33]:
# Task 27: Solve system using inverse
A = np.array([[2,-3,1],[1,-1,2],[3,1,-1]])
Bv = np.array([-1,-3,9])
np.linalg.inv(A).dot(Bv)

array([ 2.,  1., -2.])

In [34]:
# Task 28: Solve using linalg.solve
np.linalg.solve(A, Bv)

array([ 2.,  1., -2.])

In [5]:
import time

In [36]:
# Task 29: Python list addition
size = 1_000_000
L1=list(range(size))
L2=list(range(size))
start=time.time()
[L1[i]+L2[i] for i in range(size)]
time.time()-start

0.21482062339782715

In [38]:
# Task 30: Numpy addition
A1=np.arange(size)
A2=np.arange(size)
start=time.time()
A1+A2
time.time()-start

0.002813100814819336

In [39]:
# Task 31: Python list multiplication
start=time.time()
[L1[i]*L2[i] for i in range(size)]
time.time()-start

0.14337372779846191

In [40]:
# Task 32: Numpy multiplication
start=time.time()
A1*A2
time.time()-start

0.0038127899169921875

In [41]:
# Task 33: Python dot product
start=time.time()
sum(L1[i]*L2[i] for i in range(size))
time.time()-start

0.11542749404907227

In [42]:
# Task 34: Numpy dot product
start=time.time()
np.dot(A1,A2)
time.time()-start

0.002096891403198242

In [43]:
# Task 35: Python matrix multiplication
import random
M1=[[random.random() for _ in range(200)] for _ in range(200)]
M2=[[random.random() for _ in range(200)] for _ in range(200)]
start=time.time(); [[sum(M1[i][k]*M2[k][j] for k in range(200)) for j in range(200)] for i in range(200)]
time.time()-start

1.462967872619629

In [6]:
# Task 36: Numpy matrix multiplication
A=np.random.random((200,200))
B=np.random.random((200,200))
start=time.time()
A@B
time.time()-start

0.005235910415649414